name: CD
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  id-token: write

env:
  AZURE_FUNCTIONAPP_NAME: cvAzureFunc  
  DOTNET_VERSION: '6.0.x'       
  ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIBTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}     
  tf_actions_working_dir: ./terraform 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master
    - name: 'Set up terraform'
      uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      working-directory: ${{ env.tf_actions_working_dir }}

    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: ${{ env.tf_actions_working_dir }}

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      working-directory: ${{ env.tf_actions_working_dir }}

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color 
      continue-on-error: true    
      working-directory: ${{ env.tf_actions_working_dir }}

    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      working-directory: ${{ env.tf_actions_working_dir }}
      run: exit 1

    - name: Terraform Apply
      id: apply
      run: terraform apply -no-color
      working-directory: ${{ env.tf_actions_working_dir }}
      
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
         creds: '{"clientId":"${{ secrets.AZURE_AD_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_AD_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIBTION_ID }}","tenantId":"${{ secrets.AZURE_AD_TENANT_ID }}"}'

    # - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
    #   uses: actions/setup-dotnet@v1
    #   with:
    #     dotnet-version: ${{ env.DOTNET_VERSION }}

    # - name: 'Run dotnet'
    #   shell: pwsh
    #   run: dotnet build --configuration Release --output ./output
    # - name: 'Run Azure Functions Action'
    #   uses: Azure/functions-action@v1
    #   with:
    #     app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
    #     package: './output'


